# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Max in Südostasien
tagline:          'Von Bangkok über Kho Phagnan nach Laos'
description:      ''
url:              http://mstoiber.github.io
baseurl:          '/'
paginate:         10

author:
  name:           'Maximilian Stoiber'
  url:            https://mstoiber.com

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/mstoiber/mstoiber.github.io
