# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Max Stoiber
tagline:          'From Travel over Techy Stuff to General News'
description:      "My personal blog, which I'll try to update regularly"
url:              http://mstoiber.com
baseurl:          '/'
paginate:         5

author:
  name:           'Maximilian Stoiber | Blog'
  url:            http://mstoiber.com

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/mstoiber/mstoiber.github.io
