# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Max in Südostasien
tagline:          'Von Thailand über Laos nach Kambodscha'
description:      'Zwei Monate in Südostasien als Backpacker unterwegs'
url:              http://mstoiber.com
baseurl:          '/'
paginate:         5

author:
  name:           'Maximilian Stoiber'
  url:            http://mstoiber.com

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/mstoiber/mstoiber.github.io
